os:
  - osx
language: swift
osx_image: xcode11
install: swift package update
script:
  - xcodebuild test -scheme Amlich -destination platform="macOS" -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
